name: Build e deploy da documentação no GitHub Pages

on:
  push:
    branches:
      - feature#242/deploy-automatico-de-docs # or master before October 2020

# on:
#   merge:
#     branch:
#       - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'github-pages-deploy'
          
